'use client'
import Slider from "react-slick"; 

const testimonials = [
    {
        id: 1,
        text: "Platform helped me to increase my sales and revenue generated by bluebase technologies.",
        author: "Serana Belluci",
        position: "Product Designer",
        img: "https://wpriverthemes.com/synck/wp-content/uploads/2023/11/testimonial-1-1.jpg",
    },
    {
        id: 2,
        text: "Bluebase gives the best service and top customer support. Really like to have more projects with you.",
        author: "Megan Clarke",
        position: "CEO, Sanlab",
        img: "https://wpriverthemes.com/synck/wp-content/uploads/2023/11/testimonial-2-1.jpeg",
    },
    {
        id: 3,
        text: "We’ve been using bluebase for a few years, It is very simple and easy to approach team and management.",
        author: "Rachel Olsem",
        position: "Full Stack Developer",
        img: "https://wpriverthemes.com/synck/wp-content/uploads/2023/11/testimonial-3-1.jpeg",
    }
];

const Testimonials = () => {

    function SampleNextArrow(props) {
        const { className, style, onClick } = props;
        return (
          <div
            className={className}
            style={{ ...style, display: "block", background: "#1351d8;" ,color:"black"}}
            onClick={onClick}
          />
        );
      }
      
      function SamplePrevArrow(props) {
        const { className, style, onClick } = props;
        return (
          <div
            className={className}
            style={{ ...style, display: "block", background: "#1351d8;" ,color:"black"}}
            onClick={onClick}
          />
        );
      }
      

    const settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 3000,
        arrows: true,
        nextArrow: <SampleNextArrow />,
        prevArrow: <SamplePrevArrow />,
        responsive: [
            {
                breakpoint: 768,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                }
            }
        ]
    };

    return (
        <section className="testimonial-area">
            <div className="custom-container">
                <Slider {...settings}>
                    {testimonials.map((testimonial) => (
                        <div key={testimonial.id} className="testimonial-item" style={{ padding: '20px' }}>
                            <div className="testimonial-item-body" >
                                <img decoding="async" className="animation-slide-right bg-shape slide-right" src="https://wpriverthemes.com/synck/wp-content/uploads/2023/11/bg-shape-3-1.svg" alt="Background Shape" />
                                <span className="platform-name">
                                    <img decoding="async" src="https://wpriverthemes.com/synck/wp-content/uploads/2023/11/icon-linkedin-1.svg" alt="Platform" />
                                </span>
                                <h2 className="text-xl text-white">{testimonial.text}</h2>
                                <p>One aspect that sets IT Services apart is their proactive approach to security. In today's digital landscape, protecting our sensitive data is of utmost importance.</p>
                                <div className="author-box d-flex align-items-center" style={{ marginTop: '15px' }}>
                                    <img src={testimonial.img} alt={testimonial.author} style={{ marginRight: '15px' }} />
                                    <div className="author-box-content">
                                        <h5 className="text-xl text-white">{testimonial.author}</h5>
                                        <p>{testimonial.position}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </Slider>
            </div>
        </section>
    );
};

export default Testimonials;
